<a href="https://colab.research.google.com/github/stcol316/ANN_banking/blob/main/ANN_Banking_Predict.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Imports


Import Libraries

In [53]:
import numpy as np
import pandas as pd
import tensorflow as tf


Import Dataset

In [54]:
dataset = pd.read_csv("Churn_Modelling.csv")
x = dataset.iloc[:, 3: -1].values
y = dataset.iloc[:, -1].values

# Encode Categorical Data


Label Encode Gender Column

In [55]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

In [56]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encode Geography Column

In [57]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers =[('encoder', OneHotEncoder(),[1])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [58]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# Split the dataset into Training and Test sets


In [59]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

#Feature Scaling

In [60]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

# Build the ANN




Initialise ANN

In [61]:
ann = tf.keras.models.Sequential()

Add Hidden Layers


In [62]:
#6 neurons and the rectifier activation function
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

Add Output Layer

In [63]:
#Binary outcome = 1 unit and sigmoid rather than softmax
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

Compiling the ANN

In [64]:
#binary so not categorical_crossentropy
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'] )

Train ANN on Training Set

In [ ]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 975us/step - loss: 0.5866 - accuracy: 0.7276
Epoch 2/100
250/250 [==============================] - 0s 918us/step - loss: 0.4776 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 872us/step - loss: 0.4545 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 904us/step - loss: 0.4416 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 0s 930us/step - loss: 0.4347 - accuracy: 0.7961
Epoch 6/100
250/250 [==============================] - 0s 922us/step - loss: 0.4302 - accuracy: 0.7971
Epoch 7/100
250/250 [==============================] - 0s 935us/step - loss: 0.4265 - accuracy: 0.7990
Epoch 8/100
250/250 [==============================] - 0s 898us/step - loss: 0.4221 - accuracy: 0.8006
Epoch 9/100
250/250 [==============================] - 0s 945us/step - loss: 0.4169 - accuracy: 0.8018
Epoch 10/100
250/250 [==============================] - 0s 898us/step - l

Predicting A Single Observation

In [70]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40,3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


Predict Test Set Results

In [72]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Confusion Matrix

In [75]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1523   72]
 [ 198  207]]


0.865