<a href="https://colab.research.google.com/github/stcol316/ANN_banking/blob/main/ANN_Banking_Predict.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Imports


Import Libraries

In [4]:
import numpy as np
import pandas as pd
import tensorflow as tf


In [ ]:
tf.__version__


Import Dataset

In [6]:
dataset = pd.read_csv("Churn_Modelling.csv")
x = dataset.iloc[:, 3: -1].values
y = dataset.iloc[:, -1].values

# Encode Categorical Data


Label Encode Gender Column

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

One Hot Encode Geography Column

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers =[('encoder', OneHotEncoder(),[1])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [14]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]
